### ISSUE TITLE
New native function

### ISSUE THREAD

**Issue by wetalq** [FakedWeiss/awesome-vjass-support#5]
Hello sir :)
You create awesome plugin. I will wait, when you add warcraft 1.31 new function. I can send for you common.j and another files with all function list from new version.

**Comment by FadedWeiss** [comment]
> Hello sir :)
> You create awesome plugin. I will wait, when you add warcraft 1.31 new function. I can send for you common.j and another files with all function list from new version.

> Hi :)
> I've received the pullrequest #8 , so you can try the latest version.
